### ISSUE TITLE
Add forecast

### ISSUE THREAD

**Issue by dasmaetthes** [qqq3/good-weather#1]
Nice app, but currently it shows only current weather.
A forecast for the next days would be nice.

**Comment by qqq3** [comment]
Hi @dasmaetthes a009c32f6b80ab33fc7cc9da7cc24a3f6ad1efad. In the coming days will have released patch.

**Comment by qqq3** [comment]
Done https://github.com/qqq3/good-weather/releases/tag/v4.0

**Comment by regagain** [comment]
Sounds great! Do you know when this update will be available on F-Droid?

**Comment by qqq3** [comment]
Hi @regagain. 4.0 not available on F-Droid because I use beta version ConstraintLayout, thus the build this version have failed. Check [buildlog](https://f-droid.org/wiki/page/org.asdtm.goodweather/lastbuild_8).

Sorry, it's my fault

**Comment by regagain** [comment]
Will this be resolved as some point, like when the beta becomes release?
Meanwhile, could you share an apk file of version 4.0?

**Comment by qqq3** [comment]
@regagain  https://github.com/qqq3/good-weather/tree/HEAD/apk
