### ISSUE TITLE
add more languages

### ISSUE THREAD

**Issue by monolifed** [qqq3/good-weather#24]
Can you place the language files on an online translation site like crowdin or hosted.weblate?

**Comment by qqq3** [comment]
I sent a request to weblate.

**Comment by monolifed** [comment]
thank you

**Comment by qqq3** [comment]
Hm, from weblate there is still no answer...

**Comment by monolifed** [comment]
It is unfortunate. They would make adding/updating translations more convenient.
I created a pull request for Turkish. I hope I did it right.

**Comment by qqq3** [comment]
Cool, I received mail from weblate admin. He added project :)
https://hosted.weblate.org/projects/good-weahter/

Tomorrow I'll set up it!

**Comment by qqq3** [comment]
Fixed url https://hosted.weblate.org/projects/good-weather

**Comment by monolifed** [comment]
Nice. I noticed that I forgot to add turkish to "arrays.xml"

`<item name="turkish">Türkçe (Turkish)</item>`
`<item name="turkish">tr_TR</item>` (or `<item name="turkish">tr</item>`?)

**Comment by qqq3** [comment]
Ok, I'll add that.

**Comment by Hanzei** [comment]
Works well. I added some translations for german

**Comment by mahula** [comment]
@Hanzei Which translatable strings where open for German translation?

**Comment by Hanzei** [comment]
@mahula mostly widget settings

**Comment by Hanzei** [comment]
Can we close this issue?

**Comment by monolifed** [comment]
I thought this has been closed
OK I will close it, Owner can reopen it if necessary
