### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [qqq3/good-weather#36]
Hi @qqq3 

I found [this app](https://play.google.com/store/apps/details?id=org.RoyalBlue.goodweather) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app...

Maybe you should take some time (one hour or something so) to check the other apps about weather information on Google Play Store, and report them to Google. I think some of them are just "Good Weather" with ads in it, and without GNU GPL, code source and your permission... If you do it, please copy-paste the links of the apps you reported in this thread, so that I can track the "Google developers" who are stealing your work. Thanks

Regards

**Comment by qqq3** [comment]
Oh, thank you!

**Comment by Poussinou** [comment]
@qqq3 I'll close this issue now since the app has been removed, but feel free to reopen it if you find another copy, and please copy-paste the link of the fake app here so that I can track the fake developper

Thanks for tacking action :)
