### ISSUE TITLE
Feature request: add option to disable weather description

### ISSUE THREAD

**Issue by beriain** [qqq3/good-weather#4]
Hi! First of all, thank you for your great app, it works very well and is visually beautiful.

I'm not reporting an issue but a doing a feature request. When a language is not supported by openweathermap, it returns the weather description in english. It's not a big problem, but most of the time, the weather icon gives enough information about the weather. So my proposal is to add and option in the settings to allow hiding the description, both from the main screen and from the widget.

Thank you for your time and have a nice day :-)

**Comment by qqq3** [comment]
Hi @beriain. Ok, I will add your idea  :+1: 
Thanks for feadback and suggestion!
