### ISSUE TITLE
Add option for transparent widget

### ISSUE THREAD

**Issue by takiainen** [qqq3/good-weather#8]
Could make user selectable option for fully transparent widget. As minimalistic as possible, the more beautiful it would be. I'd like to see it without any colour header bars. Just temperature and maybe a cloud/rain/snow symbol and nothing more. Or maybe user could choose whether he wants to add location too in the widget?

Anyway, I ask for as minimalistic as possible and transparent.

**Comment by ascuccaro** [comment]
I support this. Either transparent or translucent would be fantastic, something like cLock's widget.

**Comment by qqq3** [comment]
[thuryn](https://github.com/thuryn) added a transparent theme. Coming soon will relese
